List<String> themeNames = [
  "Adapta Nokto",
  "Arc Dark",
  "Arc Green",
  "Aritim Dark",
  "BIB Green",
  "Bittersweet",
  "Black",
  "Black - Purple",
  "Bloody",
  "BreezeLight",
  "Burnt Sienna",
  "Challenger Deep",
  "Cherry Blossom",
  "Cherry Blossom - Coral",
  "DanDrumStone",
  "DanDrumStoneNew",
  "Dark",
  "Deep Coral",
  "Dobbo",
  "Dracula",
  "Dribbblish",
  "Dribbblish - White",
  "Dribbblish - Dark",
  "Dribbblish - Dracula",
  "Dribbblish - Gruvbox",
  "Dribbblish - Nord Dark",
  "Dribbblish - Nord Light",
  "Dribbblish - Horizon",
  "Dribbblish - Samourai",
  "Dribbblish - Purple",
  "Elementary",
  "Elementary - Blue Contrast",
  "Flatten",
  "Gradianto",
  "Gruvbox Gold",
  "Honne",
  "Jarvis Bot",
  "Kaapi",
  "Kaapi - Gruvbox",
  "Lovelace",
  "Material Ocean",
  "Midnight Light",
  "Moon Child",
  "Night",
  "Night Moon",
  "Night Owl",
  "Nord",
  "No Sleep",
  "One Darkish",
  "Onepunch",
  "Otto",
  "Outrun Dark",
  "Outrun Dark - Dark",
  "Phosphoria",
  "Pop Dark",
  "Shadow Custom",
  "Solarized Dark",
  "Spicy",
  "Sweet",
  "Treky Goldenrod",
  "Twasi",
  "Tycho Awake",
  "Vaporwave - New Retro",
  "Vaporwave - Sea Punk",
  "VPFut",
  "Wintergatan Blueprint",
  "YouTube Dark"
];
